### PR TITLE
Specify bright colours first to match base16 specification

### PR DESCRIPTION
**Pull request by JamyGolden**
I decided against merging this last week since I didn't feel like we had a strong reason to change the base24 spec, but I think a strong reason to change it is that it is most intuitive to keep base00-base0F the same in both the base16 scheme and base24 scheme when creating a base24 scheme. 

## What is a "Bright" colour?

A bright colour is perceived "bright" typically when the luminance and the saturation are higher values compared to another colour.

## Examples of current spec not being intuitive

- Here is an example of someone creating a new base16 and base24 scheme, but they keep base00-base0F the same in both schemes, even though the base24 specification specifies keeping "brighter" colours as base12-base17. It's not intuitive at all to create a base16 theme, and then swap base08, base0A-base0E with base12-base17. https://github.com/tinted-theming/schemes/pull/31
- Even though the base24 spec stipulates different, the current base24 themes actually have the "Bright" colours as base08-base0E in most cases.

CleanShot 2024-09-08 at 00 09 43@2x

The proposed PR change would actually make most of the base24 schemes fall in line with the spec

### CODE REVIEW

**Comment by FredHappyface** [comment]
My understanding with the colour palettes given are that bases 12-17 are 'lighter' than bases 8 to A, which appear more saturated. To clarify, is the understanding that these are the 'bright' colours? If so I actually think it might be worth clarifying this, that the most saturated colours are bases 8 to A 

Thoughts?

**Comment by JamyGolden** [comment]
Yeah sounds good, I've added a line to define "Bright" - I'm happy to change anything about it.

**Comment by FredHappyface** [comment]
> Yeah sounds good, I've added a line to define "Bright" - I'm happy to change anything about it.

In those examples the brighter colurs have higher saturation but *not* higher luminance 

In many cases I had decided what I thought were bright colours by increading the luminance by 10 percentage points (certainly not suggesting that was right, but more background on what I did at the time)

That said, I'm happy for bright to mean both lighter (more luminance) and more saturated

**Comment by JamyGolden** [comment]
Yeah I get that. It’s complicated with colours and something can seem “brighter” with a certain colour even if it’s technically not. A milky colour might not seem brighter compared to a more saturated colour, but a milk red is brighter than a dark red. It all depends on the colours in that palette and isn’t really something we can strictly define. 

I think we could say “Bright” refers to intensity, vividness or luminance of the colour. At the end of the day it doesn’t really matter too much as long as the two colours are different variants of the same colour.

**Comment by JamyGolden** [comment]
We could also add an image for clarity (even though it's not a hard rule):
Screenshot from 2024-09-11 10-12-58

**Review by FredHappyface — APPROVED** [review]

**Pull request merged**
